# Generated by Django 5.1 on 2024-08-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'verbose_name': 'Jobs', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterModelOptions(
            name='referencias',
            options={'verbose_name': 'Referências', 'verbose_name_plural': 'Referências'},
        ),
        migrations.AlterField(
            model_name='jobs',
            name='prazo_entrega',
            field=models.DateField(),
        ),
    ]
